### ISSUE TITLE
Domain name extraction seems incorrect

### ISSUE THREAD

**Issue by jamesbirtles** [a11ywatch/kayle#2]
I'm not totally sure what the intended output is here, but i'm pretty sure the last branch of this code always panics.
https://github.com/a11ywatch/kayle/blob/7a9d96c2aa54f4027ee41fe6f67e96d93d33676e/kayle_innate/src/lib.rs#L24-L30

If I follow `b.len()` through here:
1. if `b.len() > 2` is false, then this must be true `b.len() <= 2`
2. if `b.len() == 2` is false, then this must be true `b.len() < 2`
3. to get here, `b.len()` (given its a usize) is either 0 or 1, so the index used here will I suppose have underflowed(?) and so the `b[b.len() - 2]` is guaranteed to panic

Since `0.4.72` I am getting a panic in the radiant_blast function through wasm, its not a super useful error but given that it started breaking after this code was introduced I am assuming this is the problem. (The url I am running against in this instance is `http://localhost:4173` if it helps)

Edit: I got much nicer error out when running on github actions for some reason, it was just saying `RuntimeError: unreachable` on my mac:
```
panicked at 'index out of bounds: the len is 1 but the index is 4294967295', src/lib.rs:29:17
```

This error pretty much confirms the above

**Comment by j-mendez** [comment]
> I'm not totally sure what the intended output is here, but i'm pretty sure the last branch of this code always panics.
> 
> https://github.com/a11ywatch/kayle/blob/7a9d96c2aa54f4027ee41fe6f67e96d93d33676e/kayle_innate/src/lib.rs#L24-L30
> 
> If I follow `b.len()` through here:
> 
> 1. if `b.len() > 2` is false, then this must be true `b.len() <= 2`
> 2. if `b.len() == 2` is false, then this must be true `b.len() < 2`
> 3. to get here, `b.len()` (given its a usize) is either 0 or 1, so the index used here will I suppose have underflowed(?) and so the `b[b.len() - 2]` is guaranteed to panic
> 
> Since `0.4.72` I am getting a panic in the radiant_blast function through wasm, its not a super useful error but given that it started breaking after this code was introduced I am assuming this is the problem. (The url I am running against in this instance is `http://localhost:4173` if it helps)
> 
> Edit: I got much nicer error out when running on github actions for some reason, it was just saying `RuntimeError: unreachable` on my mac:
> 
> ```
> panicked at 'index out of bounds: the len is 1 but the index is 4294967295', src/lib.rs:29:17
> ```
> 
> This error pretty much confirms the above

@jamesbirtles thanks for the issue. I can take a look shortly, I think the else condition needs to change to - 1.

**Comment by j-mendez** [comment]
@jamesbirtles looks like that part of the logic was off https://github.com/a11ywatch/kayle/commit/7ba5dc75849b2ac8f8c500b2eac4b4a16bb1e4d4. The issue was most likely coming from this repo https://github.com/a11ywatch/crawler/commit/c4cf2715a3cb491860820837e6a0c18b778acb6b. Good work on figuring out the error location!
