### ISSUE TITLE
1_4_6_G18_or_G145.BgGradient - missing English text

### ISSUE THREAD

**Issue by tomkins** [a11ywatch/kayle#26]
Hi there - little bit new to this tool!

Currently getting the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
```

Which I believe is related to: https://github.com/a11ywatch/kayle/commit/32e073a62338981e16fb1a6a5b167bbf528b58e4#diff-e2e307ea88b3bc91933ecfc6e82696f4cd89f9a373bb1a649e2e9ef8127369b2R90

As:

```
HTMLCS.getTranslation("1_4_6_G18_or_G145.BgGradient");
undefined
```

getTranslation returns undefined for strings it can't find, and can't run replace on it.

**Comment by j-mendez** [comment]
thank you @tomkins  fixed in `v0.8.59`
